services:
  db:
    image: postgres:16-alpine
    container_name: cars_db
    restart: always
    environment:
      POSTGRES_USER: carsuser
      POSTGRES_PASSWORD: carspass
      POSTGRES_DB: carsdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: almasik04/cars:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8686:8686"
    environment:
      DATABASE_URL: postgres://carsuser:carspass@db:5432/carsdb?sslmode=disable

volumes:
  db_data:
